### ISSUE TITLE
Normalized  paths not present in AppMaps with shallow-recorded spring framework classes

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-java#104]
For the same app & appmap.jar, the HTTP server request events are different:

without spring framework events:
```json
            "event": "call",
            "http_server_request": {
                "normalized_path_info": "/owners/:ownerId",
                "path_info": "/owners/2",
                "protocol": "HTTP/1.1",
                "request_method": "GET"
            },
```
with spring framework events:

```json
            "event": "call",
            "http_server_request": {
                "path_info": "/owners/2",
                "protocol": "HTTP/1.1",
                "request_method": "GET"
            },
```

appmap.yml:
```yaml
name: spring-petclinic
# Your project contains the directory src/main/java.
# AppMap has auto-detected the following Java packages in this directory:
packages:
- path: org.springframework.samples.petclinic
- path: org.springframework.web
  shallow: true
  exclude:
    - org.springframework.web.filter.OncePerRequestFilter
 ```

[FindOwnerDavis.appmap.json.zip](https://github.com/applandinc/appmap-java/files/7093010/FindOwnerDavis.appmap.json.zip)
[Spring_Find_Owner.appmap.json.zip](https://github.com/applandinc/appmap-java/files/7093011/Spring_Find_Owner.appmap.json.zip)
