### ISSUE TITLE
Bug: Integration tests of ShardingSphere broken by AppMap agent

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-java#105]
Repo: https://github.com/apache/shardingsphere (requires JDK 8)

appmap.yml:
```yaml
name: shardingsphere
packages:
- path: org.apache.shardingsphere
```

`mvn verify` in ./shardingsphere-test/shardingsphere-integration-test

[shardingsphere_integration-tests_error.log](https://github.com/applandinc/appmap-java/files/7146151/shardingsphere_integration-tests_error.log)
