### ISSUE TITLE
Bug: bxbot test broken by appmap-java agent

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-java#108]
Repo: https://github.com/gazbert/bxbot

appmap.yml:

```yaml
name: bxbot
packages:
  - path: com.gazbert.bxbot
```

`mvn test`

[bxbot-test_error.log](https://github.com/applandinc/appmap-java/files/7146520/bxbot-test_error.log)
